#Local MongoDB config
#spring.data.mongodb.authentication-database=admin
#spring.data.mongodb.username=root
#spring.data.mongodb.password=root
#spring.data.mongodb.database=tienda
#spring.data.mongodb.port=27017
#spring.data.mongodb.host=localhost

spring:
  data:
    mongodb:
      username: root
      password: root
      database: tienda
      port: 27017
      host: localhost
  application:
    name: Store
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: 1234
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
multipart:
  maxFileSize: 10MB
  maxRequestSize: 10MB
# App config
server:
  port: 8080
